[package]
name = "ctree"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clonetree = { path = "../clonetree" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
